version: '3'

services:
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
    environment:
      # Use no authentication to allow simple access to the database from the code
      - NEO4J_AUTH=none

volumes:
  neo4j_data:
